networks:
  proxy:
    external: true
  servarrnetwork:
    name: servarrnetwork
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    profiles: ["vpn"]
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.7
      proxy:
    ports:
      - ${FIREWALL_VPN_INPUT_PORTS}:${FIREWALL_VPN_INPUT_PORTS}
      - 8080:8080
      - 6881:6881
      - 6789:6789
      - 9696:9696
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    profiles: ["vpn"]
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS}
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}:/data
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun

    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  qbittorrent-direct:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    profiles: ["no-vpn"]
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}:/data
    ports:
      - 8080:8080
      - 6881:6881
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.11
      proxy:
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    profiles: ["vpn"]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
      - ${DATA_DIR}:/data
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun

    restart: unless-stopped

  prowlarr-direct:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    profiles: ["no-vpn"]
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 9696:9696
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.12
      proxy:

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/homarr/appdata:/app/data
    environment:
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
    ports:
      - "7575:7575"
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.10
      proxy:

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 8989:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.3
      proxy:

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 7878:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.4
      proxy:

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 8686:8686
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.5
      proxy:

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 6767:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.6
      proxy:
  readarr:
    image: ghcr.io/hotio/readarr
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/readarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 8787:8787
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.9
      proxy:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - 8191:8191
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.8
